### ISSUE TITLE
run flutter failed

### ISSUE THREAD

**Issue by ping996** [chinmaygarde/flutter_wayland#4]
I have build your project successfully, the flutter_wayland is runing ok, when I add the asset path, the error happened,
flutter doctor with no errors!

Engine run configuration was invalid
Could not launch the engine with configuration.

the weston is running when I do flutter_wayland operation.
any suggestions?

**Comment by ping996** [comment]
@chinmaygarde Hi, how to use your given flutter to make the application bundle? I can't find the given flutter tool.

**Comment by ping996** [comment]
Need to checkout the flutter sdk to 5ab9e70727d858def3a586db7fb98ee580352957

**Comment by liangyk123** [comment]
Can you briefly talk about how to checkout the flutter sdk
